name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - name: Baixar código do GitHub
        uses: actions/checkout@v4

      - name: Instalar Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy das Edge Functions
        run: |
          supabase functions deploy \
            --project-ref $SUPABASE_PROJECT_ID \
            --use-api
